//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPracticaConLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Detalle = new HashSet<Detalle>();
        }
    
        public int FacturasID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> VendedorId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> MetodoPagoID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Vendedores Vendedores { get; set; }
    }
}
