//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPracticaConLoginSearchYList
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Detalle = new HashSet<Detalle>();
        }
    
        public int ProductoId { get; set; }
        [Display(Name = "Codigo UPC")]
        public string CodigoUPC { get; set; }
        [Required(ErrorMessage = "El nombre de producto es obligatorio")]

        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El precio es obligatorio")]
        [DataType(DataType.Currency)]


        [Range(1, 1000000, ErrorMessage = "Ingrese una cantidad mayor que 1")]
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> Activo { get; set; }
        [Required(ErrorMessage = "El stock es obligatorio")]

        public Nullable<int> Stock { get; set; }
        public Nullable<int> CategoriaID { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
    }
}
